-- 五子棋 (Gomoku) tables — SHARED DATABASE (also hosts DDZ's tables).
--
-- ⚠️ Hand-written, NOT generated by `drizzle-kit generate` — that command emits
-- CREATE TABLE for the shared `users`/`allowed_emails` too, which would clobber
-- DDZ's data. This file creates ONLY the two new wuziqi_* tables and references
-- the existing `users` table. Everything is IF NOT EXISTS so it is safe to
-- re-run and never touches DDZ's `users`, `allowed_emails`, `game_results`, or
-- `game_players`. (SPEC_WUZIQI §3 migration discipline.)

CREATE TABLE IF NOT EXISTS "wuziqi_results" (
  "id"           serial PRIMARY KEY NOT NULL,
  "played_at"    timestamp with time zone DEFAULT now() NOT NULL,
  "winner_color" text NOT NULL,                       -- 'black' | 'white' | 'draw'
  "win_reason"   text NOT NULL,                        -- 'five' | 'timeout' | 'resign' | 'disconnect' | 'draw'
  "board_size"   integer DEFAULT 15 NOT NULL,
  "moves"        jsonb DEFAULT '[]'::jsonb NOT NULL    -- [{ color, x, y }] in play order
);

CREATE TABLE IF NOT EXISTS "wuziqi_players" (
  "game_id" integer,
  "uid"     text,
  "color"   text NOT NULL,                             -- 'black' | 'white'
  "won"     boolean NOT NULL,
  CONSTRAINT "wuziqi_players_game_id_uid_pk" PRIMARY KEY ("game_id", "uid")
);

-- FKs (added separately so re-runs don't error on duplicate constraints).
DO $$ BEGIN
  ALTER TABLE "wuziqi_players"
    ADD CONSTRAINT "wuziqi_players_game_id_wuziqi_results_id_fk"
    FOREIGN KEY ("game_id") REFERENCES "public"."wuziqi_results"("id") ON DELETE cascade;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "wuziqi_players"
    ADD CONSTRAINT "wuziqi_players_uid_users_uid_fk"
    FOREIGN KEY ("uid") REFERENCES "public"."users"("uid");
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "idx_wuziqi_players_uid" ON "wuziqi_players" USING btree ("uid");
CREATE INDEX IF NOT EXISTS "idx_wuziqi_results_id_desc" ON "wuziqi_results" USING btree ("id" DESC NULLS LAST);
